# Generated by Django 4.2.16 on 2024-10-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_tutor_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="classes",
        ),
        migrations.AddField(
            model_name="customuser",
            name="classes",
            field=models.ManyToManyField(blank=True, to="accounts.class"),
        ),
        migrations.AddField(
            model_name="tutor",
            name="classes",
            field=models.ManyToManyField(blank=True, to="accounts.class"),
        ),
    ]
