# Generated by Django 4.2.16 on 2024-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_tutor_fun_fact_tutor_major"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="friday_hours",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="thursday_hours",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="tuesday_hours",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="wednesday_hours",
        ),
        migrations.AddField(
            model_name="tutor",
            name="classes_tutored",
            field=models.ManyToManyField(related_name="tutors", to="accounts.class"),
        ),
    ]
