# Generated by Django 4.2.16 on 2024-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_tutor_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="suggested_classes",
        ),
        migrations.AlterField(
            model_name="tutor",
            name="classes_tutored",
            field=models.ManyToManyField(
                blank=True, related_name="tutors", to="accounts.class"
            ),
        ),
    ]
