# Generated by Django 4.2.16 on 2024-10-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_remove_tutor_classes_remove_tutor_suggested_classes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="classes_tutored",
        ),
        migrations.AddField(
            model_name="tutor",
            name="classes_tutored",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
